version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-pol
    restart: always
    environment:
      POSTGRES_DB: processos_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
